#ifndef __MDM_OBJECTID_H__
#define __MDM_OBJECTID_H__


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file mdm_objectid.h 
 * \brief Automatically generated header file mdm_objectid.h
 */


/*! \brief InternetGatewayDevice. */
#define MDMOID_IGD  1

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_DebugPortMirrorCfg. */
#define MDMOID_DEBUG_PORT_MIRROR_CFG  2

/*! \brief InternetGatewayDevice.ACTIVATION_DISCOVERY. */
#define MDMOID_ACTIVATION_DISCOVERY  3

/*! \brief InternetGatewayDevice.ActivationBBIBackup. */
#define MDMOID_BBI_BACKUP  4

/*! \brief InternetGatewayDevice.DeviceInfo. */
#define MDMOID_IGD_DEVICE_INFO  5

/*! \brief InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}. */
#define MDMOID_VENDOR_CONFIG_FILE  6

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR. */
#define MDMOID_STOLLMANN_CALL_MNGR  7

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.General. */
#define MDMOID_CALLMNGR_GENERAL  8

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Account.{i}. */
#define MDMOID_CALLMNGR_ACCOUNT  9

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Device.{i}. */
#define MDMOID_CALLMNGR_DEVICE  10

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.CodecList.{i}. */
#define MDMOID_CALLMNGR_CODEC_LIST  11

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.CodecList.{i}.Codec.{i}. */
#define MDMOID_CALLMNGR_CODEC  12

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.DialPlanList.{i}. */
#define MDMOID_CALLMNGR_DIAL_PLAN_LIST  13

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.DialPlanList.{i}.DialPlan.{i}. */
#define MDMOID_CALLMNGR_DIAL_PLAN  14

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Isdn. */
#define MDMOID_CALLMNGR_ISDN  15

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.CallLogging. */
#define MDMOID_CALLMNGR_CALL_LOGGING  16

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.CallLogging.Entries.{i}. */
#define MDMOID_CALLMNGR_CALL_LOGGING_ENTRIES  17

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Phonebook. */
#define MDMOID_CALLMNGR_PHONEBOOK  18

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Phonebook.Entries.{i}. */
#define MDMOID_CALLMNGR_PHONEBOOK_ENTRIES  19

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Phonebook.Entries.{i}.Numbers.{i}. */
#define MDMOID_CALLMNGR_NUMBERS  20

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Dect. */
#define MDMOID_CALLMNGR_DECT  21

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Alerting. */
#define MDMOID_CALLMNGR_ALERTING  22

/*! \brief InternetGatewayDevice.X_STOLLMANN_COM_CALLMNGR.Alerting.Alarm.{i}. */
#define MDMOID_CALLMNGR_ALARM  23

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_BpaApiFlowHandle.{i}. */
#define MDMOID_BPA_API_FLOW_HANDLE  24

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SyslogCfg. */
#define MDMOID_SYSLOG_CFG  25

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_LoginCfg. */
#define MDMOID_LOGIN_CFG  26

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_LoginCfg.X_5067F0_Login_Group.{i}. */
#define MDMOID_LOGIN_GRP  27

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_LoginCfg.X_5067F0_Login_Group.{i}.Use_Login_Info.{i}. */
#define MDMOID_USER_LOGIN_INFO  28

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg. */
#define MDMOID_APP_CFG  29

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.HttpdCfg. */
#define MDMOID_HTTPD_CFG  30

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.Tr69cCfg. */
#define MDMOID_TR69C_CFG  31

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.Tr64cCfg. */
#define MDMOID_TR64C_CFG  32

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SshdCfg. */
#define MDMOID_SSHD_CFG  33

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.TelnetdCfg. */
#define MDMOID_TELNETD_CFG  34

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.ConsoledCfg. */
#define MDMOID_CONSOLED_CFG  35

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SmdCfg. */
#define MDMOID_SMD_CFG  36

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SskCfg. */
#define MDMOID_SSK_CFG  37

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.SnmpdCfg. */
#define MDMOID_SNMPD_CFG  38

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.FtpdCfg. */
#define MDMOID_FTPD_CFG  39

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.TftpdCfg. */
#define MDMOID_TFTPD_CFG  40

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.PppdCfg. */
#define MDMOID_PPPD_CFG  41

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.IcmpCfg. */
#define MDMOID_ICMP_CFG  42

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.UpnpCfg. */
#define MDMOID_UPNP_CFG  43

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.DnsProxyCfg. */
#define MDMOID_DNS_PROXY_CFG  44

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.DectdCfg. */
#define MDMOID_DECTD_CFG  45

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.VectoringCfg. */
#define MDMOID_VECTORING_CFG  46

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OmcidCfg. */
#define MDMOID_OMCID_CFG  47

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.LaserdCfg. */
#define MDMOID_LASERD_CFG  48

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OmciPmdCfg. */
#define MDMOID_OMCI_PMD_CFG  49

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AppCfg.OsgidCfg. */
#define MDMOID_OSGID_CFG  50

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_EthernetSwitch. */
#define MDMOID_ETHERNET_SWITCH  51

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_PwrMngtCfg. */
#define MDMOID_PWR_MNGT  52

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_StandbyCfg. */
#define MDMOID_STANDBY_CFG  53

/*! \brief InternetGatewayDevice.DeviceConfig. */
#define MDMOID_DEVICE_CONFIG  54

/*! \brief InternetGatewayDevice.ManagementServer. */
#define MDMOID_MANAGEMENT_SERVER  55

/*! \brief InternetGatewayDevice.ManagementServer.ManageableDevice.{i}. */
#define MDMOID_MANAGEABLE_DEVICE  56

/*! \brief InternetGatewayDevice.Time. */
#define MDMOID_TIME_SERVER_CFG  57

/*! \brief InternetGatewayDevice.UserInterface. */
#define MDMOID_USER_INTERFACE_CFG  58

/*! \brief InternetGatewayDevice.Layer2Bridging. */
#define MDMOID_L2_BRIDGING  59

/*! \brief InternetGatewayDevice.Layer2Bridging.Bridge.{i}. */
#define MDMOID_L2_BRIDGING_ENTRY  60

/*! \brief InternetGatewayDevice.Layer2Bridging.Filter.{i}. */
#define MDMOID_L2_BRIDGING_FILTER  61

/*! \brief InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}. */
#define MDMOID_L2_BRIDGING_INTF  62

/*! \brief InternetGatewayDevice.QueueManagement. */
#define MDMOID_Q_MGMT  63

/*! \brief InternetGatewayDevice.QueueManagement.Classification.{i}. */
#define MDMOID_Q_MGMT_CLASSIFICATION  64

/*! \brief InternetGatewayDevice.QueueManagement.Policer.{i}. */
#define MDMOID_Q_MGMT_POLICER  65

/*! \brief InternetGatewayDevice.QueueManagement.Queue.{i}. */
#define MDMOID_Q_MGMT_QUEUE  66

/*! \brief InternetGatewayDevice.LANConfigSecurity. */
#define MDMOID_LANCONFIG_SECURITY  67

/*! \brief InternetGatewayDevice.RemoteConfigSecurity. */
#define MDMOID_REMOTE_CONFIG_SECURITY  68

/*! \brief InternetGatewayDevice.RemoteConfigSecurity.UserRemoteCfg. */
#define MDMOID_USER_REMOTE_CFG  69

/*! \brief InternetGatewayDevice.RemoteConfigSecurity.ServiceRemoteCfg. */
#define MDMOID_SERVICE_REMOTE_CFG  70

/*! \brief InternetGatewayDevice.IPPingDiagnostics. */
#define MDMOID_IP_PING_DIAG  71

/*! \brief InternetGatewayDevice.Capabilities. */
#define MDMOID_CAP  72

/*! \brief InternetGatewayDevice.Capabilities.PerformanceDiagnostic. */
#define MDMOID_PERF_DIAG  73

/*! \brief InternetGatewayDevice.DownloadDiagnostics. */
#define MDMOID_DOWNLOAD_DIAG  74

/*! \brief InternetGatewayDevice.UploadDiagnostics. */
#define MDMOID_UPLOAD_DIAG  75

/*! \brief InternetGatewayDevice.UDPEchoConfig. */
#define MDMOID_UDP_ECHO_CONFIG  76

/*! \brief InternetGatewayDevice.EponSoftwareImage.{i}. */
#define MDMOID_EPON_SOFTWARE_IMAGE  77

/*! \brief InternetGatewayDevice.LANDevice.{i}. */
#define MDMOID_LAN_DEV  78

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}. */
#define MDMOID_LANHPNA_INTERFACE_CONFIG  79

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.Stats. */
#define MDMOID_STATS  80

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PerformanceMonitoring. */
#define MDMOID_PERFORMANCE_MONITORING  81

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PerformanceMonitoring.Nodes. */
#define MDMOID_NODES  82

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PerformanceMonitoring.Nodes.Previous.{i}. */
#define MDMOID_PREVIOUS  83

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PerformanceMonitoring.Nodes.Current.{i}. */
#define MDMOID_CURRENT  84

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PerformanceMonitoring.Channels. */
#define MDMOID_CHANNELS  85

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PerformanceMonitoring.Channels.Channel.{i}. */
#define MDMOID_CHANNEL  86

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PHYDiagnostics. */
#define MDMOID_PHY_DIAGNOSTICS  87

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHPNAInterfaceConfig.{i}.PHYDiagnostics.Result.{i}. */
#define MDMOID_RESULT  88

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IgmpSnoopingConfig. */
#define MDMOID_IGMP_SNOOPING_CFG  89

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement. */
#define MDMOID_LAN_HOST_CFG  90

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPStaticAddress.{i}. */
#define MDMOID_DHCP_STATIC_ADDR  91

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}. */
#define MDMOID_LAN_IP_INTF  92

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_TELEFONICA-ES_IPv6LanIntfAddress. */
#define MDMOID_I_PV6_LAN_INTF_ADDR  93

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_TELEFONICA-ES_IPv6LanIntfAddress.DelegatedAddress.{i}. */
#define MDMOID_DELEGATED_ADDRESS  94

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_TELEFONICA-ES_IPv6InterfaceAddressingType. */
#define MDMOID_I_PV6_INTF_ADDR_TYPE  95

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_LAN_IP_INTF_FIREWALL_EXCEPTION  96

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_BROADCOM_COM_IpFilterCfg.{i}. */
#define MDMOID_IP_FILTER_CFG  97

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPOption.{i}. */
#define MDMOID_LAN_HOST_OPTION  98

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}. */
#define MDMOID_DHCP_CONDITIONAL_SERVING  99

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.DHCPOption.{i}. */
#define MDMOID_DHCP_COND_SERV_OPTION  100

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement. */
#define MDMOID_I_PV6_LAN_HOST_CFG  101

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.DHCPv6StaticAddress.{i}. */
#define MDMOID_DHCPV6_STATIC_ADDR  102

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.ServerType. */
#define MDMOID_DHC_PV6_SERVER_TYPE  103

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.ServerType.StatefullDHCPv6. */
#define MDMOID_DHC_PV6_STATEFULL  104

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.IPv6SitePrefixConfigType. */
#define MDMOID_I_PV6_SITE_PREFIX_CFG  105

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.IPv6PDWanConnection. */
#define MDMOID_PD_WAN_CONN  106

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.IPv6InterfaceNumberOfEntries. */
#define MDMOID_I_PV6_INTF_NUM_OF_ENTRIES  107

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.RADVD. */
#define MDMOID_RADVD  108

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.RadVDConfigManagement. */
#define MDMOID_RADVD_CONFIG_MGT  109

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.RadVDConfigManagement.ULAPrefixInfo. */
#define MDMOID_ULA_PREFIX_INFO  110

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IPv6LANHostConfigManagement.RadVDConfigManagement.PrefixInformation.{i}. */
#define MDMOID_PREFIX_INFO  111

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_IPv6LANHostConfigManagement.X_BROADCOM_COM_MldSnoopingConfig. */
#define MDMOID_MLD_SNOOPING_CFG  112

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}. */
#define MDMOID_LAN_ETH_INTF  113

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_ETH_INTF_STATS  114

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}. */
#define MDMOID_LAN_USB_INTF  115

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_USB_INTF_STATS  116

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}. */
#define MDMOID_LAN_WLAN  117

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}. */
#define MDMOID_LAN_WLAN_ASSOCIATED_DEVICE_ENTRY  118

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}. */
#define MDMOID_LAN_WLAN_WEP_KEY  119

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}. */
#define MDMOID_LAN_WLAN_PRE_SHARED_KEY  120

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.Stats. */
#define MDMOID_LAN_WLAN_STATS  121

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter. */
#define MDMOID_WLAN_ADAPTER  122

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlBaseCfg. */
#define MDMOID_WL_BASE_CFG  123

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlStaticWdsCfg.{i}. */
#define MDMOID_WL_STATIC_WDS_CFG  124

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlWdsCfg.{i}. */
#define MDMOID_WL_WDS_CFG  125

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlScanWdsCfg.{i}. */
#define MDMOID_WL_SCAN_WDS_CFG  126

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlMimoCfg. */
#define MDMOID_WL_MIMO_CFG  127

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlSesCfg. */
#define MDMOID_WL_SES_CFG  128

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}. */
#define MDMOID_WL_VIRT_INTF_CFG  129

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlMacFltCfg.{i}. */
#define MDMOID_WL_MAC_FLT  130

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlKey64Cfg.{i}. */
#define MDMOID_WL_KEY64_CFG  131

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlKey128Cfg.{i}. */
#define MDMOID_WL_KEY128_CFG  132

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlWpsCfg. */
#define MDMOID_WL_WPS_CFG  133

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_BROADCOM_COM_WLANVirtMbssConfiguration.{i}. */
#define MDMOID_LAN_WLAN_VIRT_MBSS  134

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS. */
#define MDMOID_LAN_WLAN_WPS  135

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS.Registrar.{i}. */
#define MDMOID_LAN_WLAN_WPS_REGISTRAR  136

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}. */
#define MDMOID_LAN_QCS_WLAN  137

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.AssociatedDevice.{i}. */
#define MDMOID_LAN_QCS_WLAN_ASSOCIATED_DEVICE_ENTRY  138

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.WEPKey.{i}. */
#define MDMOID_LAN_QCS_WLAN_WEP_KEY  139

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.PreSharedKey.{i}. */
#define MDMOID_LAN_QCS_WLAN_PRE_SHARED_KEY  140

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.Stats. */
#define MDMOID_LAN_QCS_WLAN_STATS  141

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter. */
#define MDMOID_QCS_WLAN_ADAPTER  142

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlBaseCfg. */
#define MDMOID_QCS_WL_BASE_CFG  143

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlStaticWdsCfg.{i}. */
#define MDMOID_QCS_WL_STATIC_WDS_CFG  144

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlWdsCfg.{i}. */
#define MDMOID_QCS_WL_WDS_CFG  145

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlScanWdsCfg.{i}. */
#define MDMOID_QCS_WL_SCAN_WDS_CFG  146

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlMimoCfg. */
#define MDMOID_QCS_WL_MIMO_CFG  147

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlSesCfg. */
#define MDMOID_QCS_WL_SES_CFG  148

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.WlVirtIntfCfg.{i}. */
#define MDMOID_QCS_WL_VIRT_INTF_CFG  149

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlMacFltCfg.{i}. */
#define MDMOID_QCS_WL_MAC_FLT  150

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlKey64Cfg.{i}. */
#define MDMOID_QCS_WL_KEY64_CFG  151

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlKey128Cfg.{i}. */
#define MDMOID_QCS_WL_KEY128_CFG  152

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.X_BROADCOM_COM_WlanAdapter.VirtIntf.{i}.WlWpsCfg. */
#define MDMOID_QCS_WL_WPS_CFG  153

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.WPS. */
#define MDMOID_LAN_QCS_WLAN_WPS  154

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_ZYXEL_QCS_WLANConfiguration.{i}.WPS.Registrar.{i}. */
#define MDMOID_LAN_QCS_WLAN_WPS_REGISTRAR  155

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}. */
#define MDMOID_LAN_MOCA_INTF  156

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}.Status. */
#define MDMOID_LAN_MOCA_INTF_STATUS  157

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANMocaInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_MOCA_INTF_STATS  158

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANEponInterfaceConfig.{i}. */
#define MDMOID_LAN_EPON_INTF  159

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_BROADCOM_COM_LANEponInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_EPON_INTF_STATS  160

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts. */
#define MDMOID_LAN_HOSTS  161

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}. */
#define MDMOID_LAN_HOST_ENTRY  162

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_TELEFONICA-ES_IGMPSnoop. */
#define MDMOID_IGMP_SNOOP  163

/*! \brief InternetGatewayDevice.WANDevice.{i}. */
#define MDMOID_WAN_DEV  164

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig. */
#define MDMOID_WAN_COMMON_INTF_CFG  165

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_XTM_Interface_Stats.{i}. */
#define MDMOID_XTM_INTERFACE_STATS  166

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig. */
#define MDMOID_WAN_DSL_INTF_CFG  167

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.X_BROADCOM_COM_BertTest. */
#define MDMOID_WAN_BERT_TEST  168

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats. */
#define MDMOID_WAN_DSL_INTF_STATS  169

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total. */
#define MDMOID_WAN_DSL_INTF_STATS_TOTAL  170

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime. */
#define MDMOID_WAN_DSL_INTF_STATS_SHOWTIME  171

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay. */
#define MDMOID_WAN_DSL_INTF_STATS_CURRENT_DAY  172

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour. */
#define MDMOID_WAN_DSL_INTF_STATS_QUARTER_HOUR  173

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.TestParams. */
#define MDMOID_WAN_DSL_TEST_PARAMS  174

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig. */
#define MDMOID_WAN_ETH_INTF  175

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.X_BROADCOM_COM_IPv6Address.{i}. */
#define MDMOID_I_PV6_ADDR  176

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats. */
#define MDMOID_WAN_ETH_INTF_STATS  177

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig. */
#define MDMOID_WAN_MOCA_INTF  178

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig.Status. */
#define MDMOID_WAN_MOCA_INTF_STATUS  179

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANMocaInterfaceConfig.Stats. */
#define MDMOID_WAN_MOCA_INTF_STATS  180

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_EponInterfaceConfig. */
#define MDMOID_WAN_EPON_INTF  181

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_EponInterfaceConfig.Stats. */
#define MDMOID_WAN_EPON_INTF_STATS  182

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_L2tpAcIntfConfig. */
#define MDMOID_L2TP_AC_INTF_CONFIG  183

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANPonInterfaceConfig. */
#define MDMOID_WAN_PON_INTF  184

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANPonInterfaceConfig.Stats. */
#define MDMOID_WAN_PON_INTF_STATUS  185

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_DIAG  186

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_PROPRIETARY_DIAG  187

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics.PeakLineNoise. */
#define MDMOID_WAN_DSL_DIAG_PLN  188

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_BROADCOM_COM_WANDSLDiagnostics.NonLinearity. */
#define MDMOID_WAN_DSL_DIAG_NON_LINEARITY  189

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}. */
#define MDMOID_WAN_CONN_DEVICE  190

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF4EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_END_TO_END_LOOPBACK_DIAG  191

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF4LoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_LOOPBACK_DIAG  192

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANATMF5EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F5_END_TO_END_LOOPBACK_DIAG  193

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANGPONLinkConfig. */
#define MDMOID_WAN_GPON_LINK_CFG  194

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_WANEPONLinkConfig. */
#define MDMOID_WAN_EPON_LINK_CFG  195

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig. */
#define MDMOID_WAN_DSL_LINK_CFG  196

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig.X_BROADCOM_COM_ATM_PARMS. */
#define MDMOID_WAN_DSL_ATM_PARAMS  197

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics. */
#define MDMOID_WAN_ATM5_LOOPBACK_DIAG  198

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPTMLinkConfig. */
#define MDMOID_WAN_PTM_LINK_CFG  199

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANEthernetLinkConfig. */
#define MDMOID_WAN_ETH_LINK_CFG  200

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_BROADCOM_COM_L2tpAcLinkConfig. */
#define MDMOID_L2TP_AC_LINK_CONFIG  201

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_ZYXEL_COM_WWANInterfaceConfig. */
#define MDMOID_WWAN_INTERFACE_CONFIG  202

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_ZyXEL_COM_WWANInterfaceConfig.Stats. */
#define MDMOID_WWAN_INTERFACE_CONFIG_STATS  203

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_ZyXEL_WWANBudgetControl. */
#define MDMOID_WWAN_BUDGET_CONTROL  204

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_ZyXEL_WWANPingCheck. */
#define MDMOID_WWAN_PING_CHECK  205

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}. */
#define MDMOID_WAN_IP_CONN  206

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.DHCPClient. */
#define MDMOID_WAN_IP_CONN_DHCP_CLNT  207

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.DHCPClient.SentDHCPOption.{i}. */
#define MDMOID_SENT_DHCP_OPT  208

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_IP_CONN_PORTMAPPING  209

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_PortTriggering.{i}. */
#define MDMOID_WAN_IP_CONN_PORT_TRIGGERING  210

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_WAN_IP_CONN_FIREWALL_EXCEPTION  211

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_MacFilterObj. */
#define MDMOID_MAC_FILTER  212

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_BROADCOM_COM_MacFilterObj.X_BROADCOM_COM_MacFilterCfg.{i}. */
#define MDMOID_MAC_FILTER_CFG  213

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats. */
#define MDMOID_WAN_IP_CONN_STATS  214

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}. */
#define MDMOID_WAN_PPP_CONN  215

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_PPP_CONN_PORTMAPPING  216

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_BROADCOM_COM_PortTriggering.{i}. */
#define MDMOID_WAN_PPP_CONN_PORT_TRIGGERING  217

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_BROADCOM_COM_FirewallException.{i}. */
#define MDMOID_WAN_PPP_CONN_FIREWALL_EXCEPTION  218

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats. */
#define MDMOID_WAN_PPP_CONN_STATS  219

/*! \brief InternetGatewayDevice.Layer3Forwarding. */
#define MDMOID_L3_FORWARDING  220

/*! \brief InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}. */
#define MDMOID_L3_FORWARDING_ENTRY  221

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_IPv6Layer3Forwarding. */
#define MDMOID_I_PV6_L3_FORWARDING  222

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_IPv6Layer3Forwarding.IPv6Forwarding.{i}. */
#define MDMOID_I_PV6_L3_FORWARDING_ENTRY  223

/*! \brief InternetGatewayDevice.Services. */
#define MDMOID_SERVICES  224

/*! \brief InternetGatewayDevice.Services.StorageService.{i}. */
#define MDMOID_STORAGE_SERVICE  225

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.UserAccount.{i}. */
#define MDMOID_USER_ACCOUNT  226

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.Capabilites. */
#define MDMOID_CAPABILITES  227

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetInfo. */
#define MDMOID_NETWORK_INFO  228

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetworkServer. */
#define MDMOID_NETWORK_SERVER  229

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.PhysicalMedium.{i}. */
#define MDMOID_PHYSICAL_MEDIUM  230

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}. */
#define MDMOID_LOGICAL_VOLUME  231

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}.Folder.{i}. */
#define MDMOID_FOLDER  232

/*! \brief InternetGatewayDevice.VoiceService.{i}. */
#define MDMOID_VOICE  233

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}. */
#define MDMOID_VOICE_CALL_LIST  234

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.NewFlag. */
#define MDMOID_VOICE_CALL_NEW_FLAG  235

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.NumberOfMissedCalls. */
#define MDMOID_VOICE_CALL_NUMBER_OF_MISSED_CALLS  236

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.Number. */
#define MDMOID_VOICE_CALL_NUMBER  237

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.Name. */
#define MDMOID_VOICE_CALL_NAME  238

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.DateTime. */
#define MDMOID_VOICE_CALL_DATE_TIME  239

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.LineName. */
#define MDMOID_VOICE_CALL_LINE_NAME  240

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.LineId. */
#define MDMOID_VOICE_CALL_LINE_ID  241

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Call.{i}.CallType. */
#define MDMOID_VOICE_CALL_TYPE  242

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_InternalName.{i}. */
#define MDMOID_VOICE_INTERNAL_NAME_LIST  243

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_InternalName.{i}.TerminalNumber. */
#define MDMOID_VOICE_TERMINAL_NUMBER  244

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_InternalName.{i}.Name. */
#define MDMOID_VOICE_INTERNAL_NAME  245

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Contact.{i}. */
#define MDMOID_VOICE_CONTACT_LIST  246

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Contact.{i}.Name. */
#define MDMOID_VOICE_CONTACT_NAME  247

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Contact.{i}.FirstName. */
#define MDMOID_VOICE_CONTACT_FIRST_NAME  248

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Contact.{i}.ContactNumber. */
#define MDMOID_VOICE_CONTACT_NUMBER  249

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Contact.{i}.Melody. */
#define MDMOID_VOICE_CONTACT_MELODY  250

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Contact.{i}.LineId. */
#define MDMOID_VOICE_CONTACT_LINE_ID  251

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_SupportList.{i}. */
#define MDMOID_VOICE_DECT_SUPPORT_LIST  252

/*! \brief InternetGatewayDevice.VoiceService.{i}.Capabilities. */
#define MDMOID_VOICE_CAP  253

/*! \brief InternetGatewayDevice.VoiceService.{i}.Capabilities.SIP. */
#define MDMOID_VOICE_CAP_SIP  254

/*! \brief InternetGatewayDevice.VoiceService.{i}.Capabilities.MGCP. */
#define MDMOID_VOICE_CAP_MGCP  255

/*! \brief InternetGatewayDevice.VoiceService.{i}.Capabilities.Codecs.{i}. */
#define MDMOID_VOICE_CAP_CODECS  256

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}. */
#define MDMOID_VOICE_PROF  257

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.ServiceProviderInfo. */
#define MDMOID_VOICE_PROF_PROVIDER  258

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.SIP. */
#define MDMOID_VOICE_PROF_SIP  259

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.SIP.EventSubscribe.{i}. */
#define MDMOID_VOICE_PROF_SIP_SUBSCRIBE  260

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.MGCP. */
#define MDMOID_VOICE_PROF_MGCP  261

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.RTP. */
#define MDMOID_VOICE_PROF_RTP  262

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.RTP.SRTP. */
#define MDMOID_VOICE_PROF_RTP_SRTP  263

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.NumberingPlan. */
#define MDMOID_VOICE_PROF_NUMBERING_PLAN  264

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.NumberingPlan.PrefixInfo.{i}. */
#define MDMOID_VOICE_PROF_NUMBERING_PLAN_PREFIX_INFO  265

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.FaxT38. */
#define MDMOID_VOICE_PROF_FAX_T38  266

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}. */
#define MDMOID_VOICE_LINE  267

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.SIP. */
#define MDMOID_VOICE_LINE_SIP  268

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.CallingFeatures. */
#define MDMOID_VOICE_LINE_CALLING_FEATURES  269

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.VoiceProcessing. */
#define MDMOID_VOICE_LINE_PROCESSING  270

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec. */
#define MDMOID_VOICE_LINE_CODEC  271

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.List.{i}. */
#define MDMOID_VOICE_LINE_CODEC_LIST  272

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Session.{i}. */
#define MDMOID_VOICE_LINE_SESSION  273

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Stats. */
#define MDMOID_VOICE_LINE_STATS  274

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_LineSetting. */
#define MDMOID_VOICE_LINE_SETTING  275

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.LineName. */
#define MDMOID_VOICE_LINE_NAME  276

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.LineId. */
#define MDMOID_VOICE_LINE_DECT_LINE_ID  277

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.AttachedHandset. */
#define MDMOID_VOICE_LINE_ATTACHED_HANDSET  278

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.Melody. */
#define MDMOID_VOICE_LINE_MELODY  279

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.DialingPrefix. */
#define MDMOID_VOICE_LINE_DIALING_PREFIX  280

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.Volumn. */
#define MDMOID_VOICE_LINE_VOLUMN  281

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.BlockedNumber. */
#define MDMOID_VOICE_LINE_BLOCKED_NUMBER  282

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.MultiCallMode. */
#define MDMOID_VOICE_LINE_MULTI_CALL_MODE  283

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.IntrusionCall. */
#define MDMOID_VOICE_LINE_INTRUSION_CALL  284

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.CLIR. */
#define MDMOID_CLI_R  285

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.CallForwarding. */
#define MDMOID_VOICE_LINE_CALL_FORWARDING  286

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_PhyIntfMgn. */
#define MDMOID_VOICE_PHY_INTF_MGN  287

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}. */
#define MDMOID_VOICE_PHY_INTF  288

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}.X_5067F0_FXS.{i}. */
#define MDMOID_VOICE_PHY_INTF_FXS  289

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}.X_5067F0_FXO.{i}. */
#define MDMOID_VOICE_PHY_INTF_FXO  290

/*! \brief InternetGatewayDevice.VoiceService.{i}.PhyInterface.{i}. */
#define MDMOID_PHY_INTF  291

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_DECT. */
#define MDMOID_DECT  292

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_DECT.X_5067F0_DECTInterface.{i}. */
#define MDMOID_DECT_INTF  293

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_ISDN. */
#define MDMOID_VOICE_ISDN  294

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_ISDNInterface.{i}. */
#define MDMOID_ISDN_INTF  295

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_PSTN.{i}. */
#define MDMOID_VOICE_PSTN  296

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Ntr. */
#define MDMOID_VOICE_NTR  297

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Ntr.History.{i}. */
#define MDMOID_VOICE_NTR_HISTORY  298

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface. */
#define MDMOID_VOICE_DECT_SYSTEM_SETTING  299

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface.Handset.{i}. */
#define MDMOID_DECT_HANDSET  300

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface.PINCode. */
#define MDMOID_VOICE_DECT_PIN_CODE  301

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface.ClockMaster. */
#define MDMOID_VOICE_DECT_CLOCK_MASTER  302

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface.ResetBase. */
#define MDMOID_VOICE_DECT_RESET_BASE  303

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface.FirmwareVersion. */
#define MDMOID_VOICE_DECT_FIRMWARE_VERSION  304

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface.HardwareVersion. */
#define MDMOID_VOICE_DECT_HARDWARE_VERSION  305

/*! \brief InternetGatewayDevice.VoiceService.{i}.DECTInterface.EEPROMVersion. */
#define MDMOID_EEPROM_VERSION  306

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Common. */
#define MDMOID_VOICE_COMMON  307

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_VoicePhoneBook.{i}. */
#define MDMOID_VOICE_PHONE_BOOK  308

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_VoiceInternalPhoneBook. */
#define MDMOID_VOICE_INTERNAL_PHONE_BOOK  309

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceInternalPhoneBook.InterfaceList.{i}. */
#define MDMOID_INTERFACE_LIST  310

/*! \brief InternetGatewayDevice.VoiceService.{i}.VoiceInternalPhoneBook.InterfaceList.{i}.PortList.{i}. */
#define MDMOID_PORT_LIST  311

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_FXO. */
#define MDMOID_VOICE_FXO  312

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_FXO.Port.{i}. */
#define MDMOID_VOICE_FXO_PORT  313

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Alerting. */
#define MDMOID_VOICE_ALERTING  314

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Alerting.Alarm.{i}. */
#define MDMOID_VOICE_ALARM  315

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Phonebook. */
#define MDMOID_PHONEBOOK  316

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Phonebook.Entries.{i}. */
#define MDMOID_PHONEBOOK_ENTRIES  317

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Phonebook.Entries.{i}.Numbers.{i}. */
#define MDMOID_PHONEBOOK_NUMBERS  318

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_DialPlanList.{i}. */
#define MDMOID_VOICE_DIAL_PLAN_LIST  319

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_DialPlanList.{i}.DialPlan.{i}. */
#define MDMOID_VOICE_DIAL_PLAN  320

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_General. */
#define MDMOID_VOICE_GENERAL  321

/*! \brief InternetGatewayDevice.VoiceService.{i}.X_5067F0_Dsp. */
#define MDMOID_VOICE_DSP  322

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SnmpCfg. */
#define MDMOID_SNMP_CFG  323

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_SecDmzHostCfg. */
#define MDMOID_SEC_DMZ_HOST_CFG  324

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_AccessTimeRestriction.{i}. */
#define MDMOID_ACCESS_TIME_RESTRICTION  325

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_UrlFilterCfg. */
#define MDMOID_URL_FILTER_CFG  326

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_UrlFilterCfg.X_BROADCOM_COM_UrlFilterListCfgObj.{i}. */
#define MDMOID_URL_FILTER_LIST  327

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_MacFilterObj. */
#define MDMOID_LAN_MAC_FILTER  328

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_MacFilterObj.X_BROADCOM_COM_MacFilterCfg.{i}. */
#define MDMOID_LAN_MAC_FILTER_CFG  329

/*! \brief InternetGatewayDevice.X_5067F0_DDnsObj. */
#define MDMOID_D_DNS  330

/*! \brief InternetGatewayDevice.X_5067F0_DDnsObj.X_BROADCOM_COM_DDnsCfg.{i}. */
#define MDMOID_D_DNS_CFG  331

/*! \brief InternetGatewayDevice.X_5067F0_LPDPrinterObj.{i}. */
#define MDMOID_LPD_PRINTER  332

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPPCfg. */
#define MDMOID_IPP_CFG  333

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DLNA. */
#define MDMOID_DLNA  334

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DLNA.DmsCfg. */
#define MDMOID_DMS_CFG  335

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DLNA.DmsCfg.ShareFolder.{i}. */
#define MDMOID_SHARE_FOLDER  336

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_DebugPortMirroringCfg.{i}. */
#define MDMOID_WAN_DEBUG_PORT_MIRRORING_CFG  337

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IPSecCfg.{i}. */
#define MDMOID_IP_SEC_CFG  338

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_CertificateCfg.{i}. */
#define MDMOID_CERTIFICATE_CFG  339

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate. */
#define MDMOID_WAPI_CERTIFICATE  340

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate.WapiAsCertificate. */
#define MDMOID_WAPI_AS_CERTIFICATE  341

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WapiCertificate.WapiIssuedCertificate. */
#define MDMOID_WAPI_ISSUED_CERTIFICATE  342

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_NetworkConfig. */
#define MDMOID_NETWORK_CONFIG  343

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_InterfaceControl. */
#define MDMOID_INTERFACE_CONTROL  344

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_P8021agCfg. */
#define MDMOID_P8021AG_CFG  345

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_IGMPCfg. */
#define MDMOID_IGMP_CFG  346

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_MLDCfg. */
#define MDMOID_MLD_CFG  347

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_IPTunnel.{i}. */
#define MDMOID_IP_TUNNEL  348

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_IPTunnel.{i}.V4inV6Tunnel.{i}. */
#define MDMOID_IPV4IN_IPV6_TUNNEL  349

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_IPTunnel.{i}.V6inV4Tunnel.{i}. */
#define MDMOID_IPV6IN_IPV4_TUNNEL  350

/*! \brief InternetGatewayDevice.X_ITU_T_ORG. */
#define MDMOID_ITU_T_ORG  351

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4. */
#define MDMOID_G_984_4  352

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement. */
#define MDMOID_EQUIPMENT_MANAGEMENT  353

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntG. */
#define MDMOID_ONT_G  354

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.Ont2G. */
#define MDMOID_ONT2_G  355

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntData. */
#define MDMOID_ONT_DATA  356

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.SoftwareImage.{i}. */
#define MDMOID_SOFTWARE_IMAGE  357

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CardHolder.{i}. */
#define MDMOID_CARD_HOLDER  358

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CircuitPack.{i}. */
#define MDMOID_CIRCUIT_PACK  359

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PowerShedding.{i}. */
#define MDMOID_POWER_SHEDDING  360

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PortMappingPackageG.{i}. */
#define MDMOID_PORT_MAPPING_PACKAGE_G  361

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement. */
#define MDMOID_ANI_MANAGEMENT  362

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.AniG.{i}. */
#define MDMOID_ANI_G  363

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.TCont.{i}. */
#define MDMOID_T_CONT  364

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortNetworkCtp.{i}. */
#define MDMOID_GEM_PORT_NETWORK_CTP  365

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemInterworkingTp.{i}. */
#define MDMOID_GEM_INTERWORKING_TP  366

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}. */
#define MDMOID_MULTICAST_GEM_INTERWORKING_TP  367

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}.MulticastAddressTable.{i}. */
#define MDMOID_GEM_INTERWORKING_TP_MULTICAST_ADDRESS_TABLE  368

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortPmHistoryData.{i}. */
#define MDMOID_GEM_PORT_PM_HISTORY_DATA  369

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetProfile.{i}. */
#define MDMOID_GAL_ETHERNET_PROFILE  370

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetPmHistoryData.{i}. */
#define MDMOID_GAL_ETHERNET_PM_HISTORY_DATA  371

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.FecPmHistoryData.{i}. */
#define MDMOID_FEC_PM_HISTORY_DATA  372

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices. */
#define MDMOID_LAYER2_DATA_SERVICES  373

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeServiceProfile.{i}. */
#define MDMOID_MAC_BRIDGE_SERVICE_PROFILE  374

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MacBridgeServiceProfile.{i}. */
#define MDMOID_BC_MAC_BRIDGE_SERVICE_PROFILE  375

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_CONFIG_DATA  376

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PM_HISTORY_DATA  377

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_CONFIG_DATA  378

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortDesignationData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_DESIGNATION_DATA  379

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_TABLE_DATA  380

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}.MacFilterTable.{i}. */
#define MDMOID_MAC_FILTER_TABLE  381

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterPreAssignTable.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_PRE_ASSIGN_TABLE  382

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_BRIDGE_TABLE_DATA  383

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}.BridgeTable.{i}. */
#define MDMOID_BRIDGE_TABLE  384

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortPmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_PM_HISTORY_DATA  385

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MapperServiceProfile.{i}. */
#define MDMOID_MAPPER_SERVICE_PROFILE  386

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MapperServiceProfile.{i}. */
#define MDMOID_BC_MAPPER_SERVICE_PROFILE  387

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingFilterData.{i}. */
#define MDMOID_VLAN_TAGGING_FILTER_DATA  388

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  389

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_EXTENDED_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  390

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}.ReceivedFrameVlanTaggingOperationTable.{i}. */
#define MDMOID_RECEIVED_FRAME_VLAN_TAGGING_OPERATION_TABLE  391

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}. */
#define MDMOID_MULTICAST_OPERATIONS_PROFILE  392

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.DynamicAccessControlListTable.{i}. */
#define MDMOID_DYNAMIC_ACCESS_CONTROL_LIST_TABLE  393

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.StaticAccessControlListTable.{i}. */
#define MDMOID_STATIC_ACCESS_CONTROL_LIST_TABLE  394

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.LostGroupsListTable.{i}. */
#define MDMOID_LOST_GROUPS_LIST_TABLE  395

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberConfigInfo.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_CONFIG_INFO  396

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_MONITOR  397

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}.ActiveGroupsListTable.{i}. */
#define MDMOID_ACTIVE_GROUPS_LIST_TABLE  398

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MulticastSubscriberMonitor.{i}. */
#define MDMOID_BC_MULTICAST_SUBSCRIBER_MONITOR  399

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_BROADCOM_COM_MulticastSubscriberMonitor.{i}.MulticastSubscriber.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER  400

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.UpstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_UPSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  401

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.DownstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_DOWNSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  402

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices. */
#define MDMOID_LAYER3_DATA_SERVICES  403

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostConfigData.{i}. */
#define MDMOID_IP_HOST_CONFIG_DATA  404

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_IpHostConfigData.{i}. */
#define MDMOID_BC_IP_HOST_CONFIG_DATA  405

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostPmHistoryData.{i}. */
#define MDMOID_IP_HOST_PM_HISTORY_DATA  406

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}. */
#define MDMOID_IPV6_HOST_CONFIG_DATA  407

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentAddressTable.{i}. */
#define MDMOID_IPV6_CURRENT_ADDRESS_TABLE  408

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDefaultRouterTable.{i}. */
#define MDMOID_IPV6_CURRENT_DEFAULT_ROUTER_TABLE  409

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDnsTable.{i}. */
#define MDMOID_IPV6_CURRENT_DNS_TABLE  410

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentOnlinkPrefixTable.{i}. */
#define MDMOID_IPV6_CURRENT_ONLINK_PREFIX_TABLE  411

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_Ipv6HostConfigData.{i}. */
#define MDMOID_BC_IPV6_HOST_CONFIG_DATA  412

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.TcpUdpConfigData.{i}. */
#define MDMOID_TCP_UDP_CONFIG_DATA  413

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices. */
#define MDMOID_ETHERNET_SERVICES  414

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.PptpEthernetUni.{i}. */
#define MDMOID_PPTP_ETHERNET_UNI  415

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA  416

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData2.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA2  417

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData3.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA3  418

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.VirtualEthernetInterfacePoint.{i}. */
#define MDMOID_VIRTUAL_ETHERNET_INTERFACE_POINT  419

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices. */
#define MDMOID_VOICE_SERVICES  420

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.PptpPotsUni.{i}. */
#define MDMOID_PPTP_POTS_UNI  421

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipUserData.{i}. */
#define MDMOID_SIP_USER_DATA  422

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentConfigData.{i}. */
#define MDMOID_SIP_AGENT_CONFIG_DATA  423

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpVoiceCtp.{i}. */
#define MDMOID_VO_IP_VOICE_CTP  424

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpMediaProfile.{i}. */
#define MDMOID_VO_IP_MEDIA_PROFILE  425

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceServiceProfile.{i}. */
#define MDMOID_VOICE_SERVICE  426

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpProfileData.{i}. */
#define MDMOID_RTP_PROFILE_DATA  427

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpAppServiceProfile.{i}. */
#define MDMOID_VO_IP_APP_SERVICE_PROFILE  428

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceFeatureAccessCodes.{i}. */
#define MDMOID_VOICE_FEATURE_ACCESS_CODES  429

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}. */
#define MDMOID_NETWORK_DIAL_PLAN_TABLE  430

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}.DialPlanTable.{i}. */
#define MDMOID_DIAL_PLAN_TABLE  431

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpLineStatus.{i}. */
#define MDMOID_VO_IP_LINE_STATUS  432

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.CallControlPmHistoryData.{i}. */
#define MDMOID_CALL_CONTROL_PM_HISTORY_DATA  433

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpPmHistoryData.{i}. */
#define MDMOID_RTP_PM_HISTORY_DATA  434

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentPmHistoryData.{i}. */
#define MDMOID_SIP_AGENT_PM_HISTORY_DATA  435

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipCallInitPmHistoryData.{i}. */
#define MDMOID_SIP_CALL_INIT_PM_HISTORY_DATA  436

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcConfigData.{i}. */
#define MDMOID_MGC_CONFIG_DATA  437

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcPmHistoryData.{i}. */
#define MDMOID_MGC_PM_HISTORY_DATA  438

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpConfigData.{i}. */
#define MDMOID_VO_IP_CONFIG_DATA  439

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices. */
#define MDMOID_MOCA_SERVICES  440

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.PptpMocaUni.{i}. */
#define MDMOID_PPTP_MOCA_UNI  441

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_PptpMocaUni.{i}. */
#define MDMOID_BRCM_PPTP_MOCA_UNI  442

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_MocaStatus.{i}. */
#define MDMOID_MOCA_STATUS  443

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_BROADCOM_COM_MocaStats.{i}. */
#define MDMOID_MOCA_STATS  444

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaEthernetPmHistoryData.{i}. */
#define MDMOID_MOCA_ETHERNET_PM_HISTORY_DATA  445

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA  446

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}.NodeTable.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA_NODE_TABLE  447

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement. */
#define MDMOID_TRAFFIC_MANAGEMENT  448

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.PriorityQueueG.{i}. */
#define MDMOID_PRIORITY_QUEUE_G  449

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.TrafficSchedulerG.{i}. */
#define MDMOID_TRAFFIC_SCHEDULER_G  450

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.GemTrafficDescriptor.{i}. */
#define MDMOID_GEM_TRAFFIC_DESCRIPTOR  451

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General. */
#define MDMOID_GENERAL  452

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.UniG.{i}. */
#define MDMOID_UNI_G  453

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.OltG. */
#define MDMOID_OLT_G  454

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.NetworkAddress.{i}. */
#define MDMOID_NETWORK_ADDRESS  455

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.AuthenticationSecurityMethod.{i}. */
#define MDMOID_AUTHENTICATION_SECURITY_METHOD  456

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.LargeString.{i}. */
#define MDMOID_LARGE_STRING  457

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData1.{i}. */
#define MDMOID_THRESHOLD_DATA1  458

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData2.{i}. */
#define MDMOID_THRESHOLD_DATA2  459

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.Omci. */
#define MDMOID_OMCI  460

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.TR069ManagementServer.{i}. */
#define MDMOID_TR069_MANAGEMENT_SERVER  461

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_OmciSystem. */
#define MDMOID_OMCI_SYSTEM  462

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_GponOmciStats. */
#define MDMOID_GPON_OMCI_STATS  463

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_DnsMasqCfg. */
#define MDMOID_DNS_MASQ_CFG  464

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_StaticDnsEntry.{i}. */
#define MDMOID_STATIC_DNS_ENTRY  465

/*! \brief InternetGatewayDevice.X_BROADCOM_COM_WlanNvram. */
#define MDMOID_WLAN_NVRAM  466

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_CIFS. */
#define MDMOID_CIFS  467

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_CIFS.CIFS.{i}. */
#define MDMOID_CIFS_DIR  468

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_CIFS.User.{i}. */
#define MDMOID_CIFS_USER  469

/*! \brief InternetGatewayDevice.X_CT_OAM. */
#define MDMOID_CTOAM  470

/*! \brief InternetGatewayDevice.X_CT_OAM.IADInfo. */
#define MDMOID_OAMIAD_INFO  471

/*! \brief InternetGatewayDevice.X_CT_OAM.GlobalParameterConfig. */
#define MDMOID_OAM_GLB_PARAM_CFG  472

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPParameterConfig. */
#define MDMOID_OAMSIP_PARAM_CFG  473

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPUserParameterConfig. */
#define MDMOID_OAMSIP_USR_PARAM_CFG  474

/*! \brief InternetGatewayDevice.X_CT_OAM.FAXModemConfig. */
#define MDMOID_OAMFAXMD_CFG  475

/*! \brief InternetGatewayDevice.X_CT_OAM.POTSStatus. */
#define MDMOID_OAMPOTS_STS  476

/*! \brief InternetGatewayDevice.X_CT_OAM.IADOperation. */
#define MDMOID_OAMIAD_OP  477

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPDigitMap. */
#define MDMOID_OAMSIP_DGT_MP  478

/*! \brief InternetGatewayDevice.SoftwareModules. */
#define MDMOID_SW_MODULES  479

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}. */
#define MDMOID_EU  480

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}.Extensions. */
#define MDMOID_EXTENSIONS  481

/*! \brief InternetGatewayDevice.SoftwareModules.ExecEnv.{i}. */
#define MDMOID_EXEC_ENV  482

/*! \brief InternetGatewayDevice.SoftwareModules.DeploymentUnit.{i}. */
#define MDMOID_DU  483

/*! \brief InternetGatewayDevice.PartialCfg. */
#define MDMOID_PARTIAL_CFG  484

/*! \brief InternetGatewayDevice.DNSRouteEntry.{i}. */
#define MDMOID_DNS_ROUTE_ENTRY  485

/*! \brief InternetGatewayDevice.Device. */
#define MDMOID_DEVICE  486

/*! \brief InternetGatewayDevice.Device.Optical. */
#define MDMOID_DEVICE_OPTICAL  487

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}. */
#define MDMOID_OPTICAL_INTERFACE  488

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}.Stats. */
#define MDMOID_OPTICAL_INTERFACE_STATS  489

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_MHSLANDevices.{i}. */
#define MDMOID_MHSLAN_DEVICES  490

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_MHSLANDevices.{i}.USBStorageInfo. */
#define MDMOID_USB_STORAGE_INFO  491

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_MHSLANDevices.{i}.USBStorageInfo.Partitions.{i}. */
#define MDMOID_PARTITIONS  492

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_MHSApplications.{i}. */
#define MDMOID_MHS_APPLICATIONS  493

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_MHSApplications.{i}.PortMappingRules.{i}. */
#define MDMOID_PORT_MAPPING_RULES  494

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_ALG. */
#define MDMOID_ALG  495

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_Firewall. */
#define MDMOID_FIREWALL  496

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_Firewall.Firewall.{i}. */
#define MDMOID_FIREWALL_CFG  497

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_Firewall.Firewall.{i}.Stats. */
#define MDMOID_FIREWALL_STATS  498

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_Firewall.Firewall.{i}.Rule.{i}. */
#define MDMOID_FIREWALL_RULE_CFG  499

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_Firewall.Firewall.{i}.Rule.{i}.Origin. */
#define MDMOID_FIREWALL_RULE_SRC_CFG  500

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_Firewall.Firewall.{i}.Rule.{i}.Destination. */
#define MDMOID_FIREWALL_RULE_DST_CFG  501

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_Firewall.Firewall.{i}.Rule.{i}.Stats. */
#define MDMOID_FIREWALL_RULE_STATS  502

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_SystemState. */
#define MDMOID_SYS_STATE  503

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_SystemState.Mem. */
#define MDMOID_SYS_MEM  504

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_SystemState.CPU. */
#define MDMOID_SYS_CPU  505

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_SystemState.NatSessionTable. */
#define MDMOID_SYS_NAT_SESSION  506

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_IGMPProxy. */
#define MDMOID_IGMP_PROXY  507

/*! \brief InternetGatewayDevice.X_TELEFONICA-ES_IGMPProxy.IGMPTable.{i}. */
#define MDMOID_IGMP_TABLE  508

/*! \brief InternetGatewayDevice.X_ZYXEL_COM_AutoexecCmd.{i}. */
#define MDMOID_AUTOEXEC_CMD  509

/*! \brief InternetGatewayDevice.X_5067F0_AccessServiceCfg. */
#define MDMOID_MSTC_ACCESS_SERVICE  510

/*! \brief InternetGatewayDevice.X_5067F0_VoipSchedule.{i}. */
#define MDMOID_VOIP_SCHEDULE  511

/*! \brief InternetGatewayDevice.X_5067F0_Schedule.{i}. */
#define MDMOID_SCHEDULE  512

/*! \brief InternetGatewayDevice.X_5067F0_AutoScheduleObj. */
#define MDMOID_MSTC_AUTO_SCHEDULE  513

/*! \brief InternetGatewayDevice.WANPortForwarding. */
#define MDMOID_WAN_PORT_FORWARD  514

/*! \brief InternetGatewayDevice.WANPortForwarding.PortMapping.{i}. */
#define MDMOID_WAN_PPP_PORTMAPPING  515

/*! \brief maximum OID value */
#define MDM_MAX_OID 515



#endif /* __MDM_OBJECTID_H__ */
